### PR TITLE
added option to enter self hosted url

### PR DESCRIPTION
**Pull request by thanesh**
this helps those who might have a self hosted plausible

### CODE REVIEW

**Comment by spekulatius** [comment]
Hello @thanesh,

Thank you for your conditions. Does it still work for the non-self hosted versions? It appears as if the default isn't in, is it?

Cheers,
Peter

**Comment by thanesh** [comment]
Good question. Default was removed with my change. Let me see if I can add back the default

Thanks

**Comment by thanesh** [comment]
Can you please check?

**Comment by spekulatius** [comment]
Hey @thanesh,

Thanks, that looks great!

I've merged it and tagged a new release! Let me know if any issues come up!

Cheers,
Peter

**Pull request merged**
